#!/usr/bin/env python3
"""
Embed binary assets (logos, etc.) into firmware as C arrays.

Inputs are listed in ASSETS below. Output is a single
src/generated/embedded_assets.{h,cpp} pair declaring
`const uint8_t kAssetName[]` and `const size_t kAssetNameLen`
for each entry.

Run:
- Automatically as a PlatformIO pre-build script (extra_scripts in platformio.ini).
- Manually: `python scripts/embed_assets.py`
"""

import os
import sys
from pathlib import Path

# Each entry: (C identifier, source path relative to project root).
# The identifier becomes `kIdent` / `kIdentLen` in C++.
ASSETS = [
    ("BootLogoPng", "assets/system/ezOS.png"),
]


def emit_array(ident: str, data: bytes) -> str:
    lines = []
    lines.append(f"extern const uint8_t k{ident}[] = {{")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"extern const size_t k{ident}Len = {len(data)};")
    return "\n".join(lines)


def embed_assets(project_root: Path) -> int:
    out_dir = project_root / "src" / "generated"
    header = out_dir / "embedded_assets.h"
    source = out_dir / "embedded_assets.cpp"
    out_dir.mkdir(parents=True, exist_ok=True)

    header_lines = [
        "// Auto-generated by scripts/embed_assets.py - do not edit.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
    ]
    source_lines = [
        "// Auto-generated by scripts/embed_assets.py - do not edit.",
        '#include "embedded_assets.h"',
        "",
    ]

    total = 0
    for ident, rel_path in ASSETS:
        path = project_root / rel_path
        if not path.is_file():
            print(f"[embed_assets] MISSING: {rel_path}", file=sys.stderr)
            return 1
        data = path.read_bytes()
        total += len(data)
        header_lines += [
            f"extern const uint8_t k{ident}[];",
            f"extern const size_t k{ident}Len;",
            "",
        ]
        source_lines.append(emit_array(ident, data))
        source_lines.append("")
        print(f"[embed_assets] {rel_path} -> k{ident} ({len(data)} bytes)")

    new_header = "\n".join(header_lines)
    new_source = "\n".join(source_lines)

    # Only rewrite if changed so PlatformIO doesn't recompile every build.
    if not header.exists() or header.read_text() != new_header:
        header.write_text(new_header)
    if not source.exists() or source.read_text() != new_source:
        source.write_text(new_source)

    print(f"[embed_assets] {len(ASSETS)} asset(s), {total} bytes total")
    return 0


# PlatformIO pre-build hook
try:
    Import("env")  # type: ignore[name-defined]
    project_dir = Path(env.get("PROJECT_DIR", "."))  # type: ignore[name-defined]
    result = embed_assets(project_dir)
    if result != 0:
        env.Exit(1)  # type: ignore[name-defined]
except NameError:
    pass


def main():
    project_root = Path(__file__).resolve().parent.parent
    return embed_assets(project_root)


if __name__ == "__main__":
    sys.exit(main())
