#!/usr/bin/env python3
"""
Produce reusable shadow/gradient PNG strips for UI polish.

Four assets are generated, all thin strips that tile cleanly to cover the
screen edges:

    shadow_top     32x12 — opaque black at top fading to transparent
    shadow_bottom  32x12 — flipped counterpart for a "more below" hint
    shadow_left    12x32 — vertical strip dark on the left
    shadow_right   12x32 — vertical strip dark on the right

The generator writes lua/ezui/shadows.lua — a small module exposing the
PNG bytes plus helpers that tile each asset across a (x, y, w, h) region.
"""

import io
from pathlib import Path

from PIL import Image, ImageDraw


STRIP_LONG = 32   # tile length along the long axis
STRIP_SHORT = 12  # thickness
MAX_ALPHA = 180   # peak alpha of the dark edge

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "lua" / "ezui" / "shadows.lua"


def gradient_strip(orientation: str) -> Image.Image:
    """Build a thin RGBA strip with an alpha gradient along `orientation`.

    orientation is one of 'top', 'bottom', 'left', 'right' — it determines
    which edge of the strip carries the opaque black and which fades out.
    """
    horizontal = orientation in ("top", "bottom")
    w = STRIP_LONG if horizontal else STRIP_SHORT
    h = STRIP_SHORT if horizontal else STRIP_LONG
    img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    px = img.load()

    if horizontal:
        for y in range(h):
            t = y / (h - 1)
            if orientation == "top":
                a = int(MAX_ALPHA * (1 - t) ** 1.5)
            else:  # bottom
                a = int(MAX_ALPHA * (t) ** 1.5)
            for x in range(w):
                px[x, y] = (0, 0, 0, a)
    else:
        for x in range(w):
            t = x / (w - 1)
            if orientation == "left":
                a = int(MAX_ALPHA * (1 - t) ** 1.5)
            else:  # right
                a = int(MAX_ALPHA * (t) ** 1.5)
            for y in range(h):
                px[x, y] = (0, 0, 0, a)

    return img


def png_bytes(img: Image.Image) -> bytes:
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def to_lua_literal(data: bytes) -> str:
    return '"' + "".join(f"\\x{b:02x}" for b in data) + '"'


LUA_TEMPLATE = """\
-- ezui.shadows: reusable shadow/gradient strips for UI polish.
--
-- Generated by tools/gen_shadows.py. Do not hand-edit; re-run the tool if
-- you want to tweak sizes or alpha.
--
-- Each strip is a thin PNG that the helpers below tile across an arbitrary
-- (x, y, w, h) region. The strips are deliberately tiny so repeated
-- draw_png calls are cheap; no state is kept between calls.
--
-- Use cases:
--   * Scroll viewports: fade the top/bottom edges of clipped content to
--     hint "more above" / "more below". ezui.layout's scroll widget calls
--     draw_scroll_edges() directly.
--   * Screen chrome: a bottom shadow under a wallpaper darkens the area
--     where the dock/labels sit so white-ish icons stay readable.

local shadows = {{}}

shadows.STRIP_LONG  = {strip_long}
shadows.STRIP_SHORT = {strip_short}

shadows.top    = {top_png}
shadows.bottom = {bottom_png}
shadows.left   = {left_png}
shadows.right  = {right_png}

-- Tile a horizontal strip (shadows.top / shadows.bottom) across width `w`.
function shadows.draw_horizontal(d, png, x, y, w)
    local step = shadows.STRIP_LONG
    local drawn = 0
    while drawn < w do
        d.draw_png(x + drawn, y, png)
        drawn = drawn + step
    end
end

-- Tile a vertical strip (shadows.left / shadows.right) across height `h`.
function shadows.draw_vertical(d, png, x, y, h)
    local step = shadows.STRIP_LONG
    local drawn = 0
    while drawn < h do
        d.draw_png(x, y + drawn, png)
        drawn = drawn + step
    end
end

-- Draw scroll-edge hints inside the viewport (x,y,w,h). `can_up` shows the
-- top shadow; `can_down` shows the bottom. Either may be nil to skip.
function shadows.draw_scroll_edges(d, x, y, w, h, can_up, can_down)
    if can_up then
        shadows.draw_horizontal(d, shadows.top, x, y, w)
    end
    if can_down then
        shadows.draw_horizontal(d, shadows.bottom, x, y + h - shadows.STRIP_SHORT, w)
    end
end

return shadows
"""


def main() -> None:
    top    = png_bytes(gradient_strip("top"))
    bottom = png_bytes(gradient_strip("bottom"))
    left   = png_bytes(gradient_strip("left"))
    right  = png_bytes(gradient_strip("right"))

    print(f"  top    = {len(top):4d}B")
    print(f"  bottom = {len(bottom):4d}B")
    print(f"  left   = {len(left):4d}B")
    print(f"  right  = {len(right):4d}B")

    lua = LUA_TEMPLATE.format(
        strip_long=STRIP_LONG,
        strip_short=STRIP_SHORT,
        top_png=to_lua_literal(top),
        bottom_png=to_lua_literal(bottom),
        left_png=to_lua_literal(left),
        right_png=to_lua_literal(right),
    )
    OUT_PATH.write_text(lua)
    print(f"\nWrote {OUT_PATH}")


if __name__ == "__main__":
    main()
